### ISSUE TITLE
Sodium FATAL ERROR v2 : HomeSpan\src\HAP.cpp:29:20: fatal error: sodium.h: No such file or directory

### ISSUE THREAD

**Issue by lilShoun** [HomeSpan/HomeSpan#697] opened 2023-11-19 18:32 UTC
I opened the 1st available test file "01-SimpleLightBulb.ino".
I ran the program's Verify. I got the following error :
```
HomeSpan\src\HAP.cpp:29:20: fatal error: sodium.h: No such file or directory
compilation terminated.

exit status 1

Compilation error: exit status 1
```
The issue #687 had already dealt with this subject. However, having followed all the information given, this error still persists with me.
I have downloaded all the ESP32 Boards. 
![image](https://github.com/HomeSpan/HomeSpan/assets/98209945/44ba56d6-00a9-46d8-92d5-b7e9c4a95fad)
![image](https://github.com/HomeSpan/HomeSpan/assets/98209945/38d52826-1035-4638-8694-1a27e010b1d3)

01-SimpleLightBulb.ino :
```
#include "HomeSpan.h"

void setup() {
  Serial.begin(115200);
  homeSpan.begin(Category::Lighting,"HomeSpan LightBulb");

  new SpanAccessory();
    new Service::AccessoryInformation();
      new Characteristic::Identify();
    new Service::LightBulb();
      new Characteristic::On();

}
void loop(){

  homeSpan.poll();
  
}
```

**Comment by HomeSpan** [comment] 2023-11-19 22:31
Remove all the ESP32 board managers above to make sure you are starting with a clean build.  Then install the esp32 (all lowercase) package from Espressif (it's the third one you have listed above).  The latest version is 2.0.14.  You'll know you have the right one if when you click on "more info" it takes you to the Espressif GitHub site.

DO NOT install anything else that says ESP32.

**Comment by carterscherer** [comment] 2024-02-29 05:52
This is now an issue again when using the 3.0.0 alpha-3 update that has the FQBN for the ESP32-H2.  HomeSpan/src/HAP.cpp:29:10: fatal error: sodium.h: No such file or directory
   29 | #include <sodium.h>

**Comment by HomeSpan** [comment] 2024-02-29 13:25
I had noticed this as well when I tried to use the new version.  The problem is that sodium and mdns are [no longer](https://docs.espressif.com/projects/esp-idf/en/v5.2/esp32c3/migration-guides/release-5.x/5.0/removed-components.html) included in the base IDF-5 framework and need to be added in through optional build commands.  Espressif shows how to do this with the IDF, but not with the Arduino-ESP32 library.  Since these are core components that have always been part of the Arduino-ESP32 library I'm guessing that the folks producing the library will incorporate them into the final product, or provide a clear hook into how they can be loaded when using the library. 

Since the library is only in alpha I assume they will get to this eventually, but have not checked.  You may want to post a question on this on the Arduino-ESP32 issues to see what they are thinking.

**Comment by harshal17** [comment] 2024-05-28 17:24
Any workaround for this error? Having the same issue with the include sodium.h. line causing an error in HAP.cpp, HomeSpan.cpp and SRP.cpp

**Comment by goodje** [comment] 2024-05-29 17:46
I also encountered the issue.

**Comment by HomeSpan** [comment] 2024-05-30 22:49
The new Arduino-ESP32 3.0 library contains MANY breaking changes (according to Espressif) because it migrates from using ESP32 IDF4 to IDF5.   Among what will likely be a host of issues, is the larger problem that the sodium library used by HomeSpan to perform many of the standard encryption/decryption methods HomeKit uses under the hood, is no longer included as part of the Ardiuno-ESP32 library.  This is a gating issue and must be solved before tackling any other problems related to the migration from 2.X to 3.X.

I have asked the Arduino-ESP32 folks for guidance on how to properly incorporate the library when using the new 3.0 version:  https://github.com/espressif/arduino-esp32/issues/9732

Will wait a few days for their response before starting to explore other solutions.

**Comment by JeremyLaurenson** [comment] 2024-06-03 16:44
I have submitted a pull request that at least generates an error telling users what to do if they have the 3.0 version updated.
https://github.com/HomeSpan/HomeSpan/pull/858

**Comment by HomeSpan** [comment] 2024-06-11 02:40
I like the idea of a check but needed to make it more generic to make it future proof against any further changes in either the HomeSpan library or the Arduino-ESP32 Board Manager.  Code is in dev branch (you'll note new file `version.h` and will be rolled out into next release).

Getting HomeSpan to work with version 3 of the Board Manager look like it will be a very heavy lift, so will not be tackling in the near term.

**Comment by Nezaemmy** [comment] 2024-06-11 11:30
> I have asked the Arduino-ESP32 folks for guidance on how to properly incorporate the library when using the new 3.0 version: [espressif/arduino-esp32#9732](https://github.com/espressif/arduino-esp32/issues/9732)
> 
Good news, they going to add libsodium to V3

**Comment by JeremyLaurenson** [comment] 2024-06-11 11:33
Awesome!

**Comment by HomeSpan** [comment] 2024-06-15 13:20
Closing this for now ---even with Sodium included, there are many other breaking changes in the 3.0 version of the board manager.  For now, I've added a check to HomeSpan informing users that it can only be compiled under version 2.0.

**Closed** 2024-06-15 13:20 UTC
