### ISSUE TITLE
poll() takes a long time

### ISSUE THREAD

**Issue by cckanne** [HomeSpan/HomeSpan#329] opened 2022-06-24 02:31 UTC
I have an accessory with a light, an air quality sensor, and an air purifier service. Sometimes it takes more than 4 seconds between the time the last loop/update call from my service implementation returns (to homespan), and the homespan.poll() code returns (to top-level loop). Is there something I can do about that?

My hardware requires a message on a serial connection every second or so, otherwise the light turns off. So any long delays cause the light to flicker.

(Very cool library BTW. Much fun is being had over here!)

**Comment by HomeSpan** [comment] 2022-06-24 03:05
Can you post a zip file of your sketch?  Is the issue that your sensor takes a while to return?

**Comment by cckanne** [comment] 2022-06-24 19:49
the structure is like this (removed a lot of the logic):

```
long lastContact;

void reportLastContact(const char *loc) {
  long now = millis();
  long duration = now - lastContact;
  if(duration > 700)
    WEBLOG("Last contact %ldms ago. Now at %s.", duration, loc);
  lastContact = now;  
}

struct DEV_Identify : Service::AccessoryInformation {
...
};

struct DEV_ZephyrLight : Service::LightBulb {

...

  boolean update() {
    reportLastContact("light update start");
    ...
    reportLastContact("light update end");
    return true;
  } // update

  void loop() {
    reportLastContact("light loop");
  }
};

struct DEV_ZephyrFan;

struct DEV_AirQuality : Service::AirQualitySensor {
  ...

  void loop() {
    reportLastContact("AQ loop start");
    if (millis() - lastReadout > 2300) {
      ...
      lastReadout = millis();
    }
    reportLastContact("AQ loop end");
  }
};

//////////////////////////////////

struct DEV_ZephyrFan : Service::AirPurifier {
  ...
  boolean update() {
    reportLastContact("vent update start");
    ...
    reportLastContact("vent update end");
    return true;
  } // update

  void loop() {
    reportLastContact("vent loop start");
...
    reportLastContact("vent loop end");
  }
};

DEV_ZephyrFan *fan;
DEV_ZephyrLight *light;

void setup() {
  Serial.begin(115200);
  Serial1.begin(4800); // zephyr hood mainboard connection

  homeSpan.setStatusPin(13);
  homeSpan.setControlPin(27);
  homeSpan.enableOTA();
  homeSpan.setQRID("ZVH1");
  homeSpan.setSketchVersion("1.0");
  homeSpan.enableWebLog(150, "pool.ntp.org", "PST", "zephyr");

  homeSpan.begin(Category::Fans, "Vent Hood");

  new SpanAccessory();
  new DEV_Identify("Vent Hood", "HomeSpan", "ZVH-1", "R", "1.0", 0);
  new Service::HAPProtocolInformation();
  new Characteristic::Version("1.1.0");
  fan = new DEV_ZephyrFan(new DEV_AirQuality());
  fan->setPrimary();
  light = new DEV_ZephyrLight();
  lastContact = millis();
}

void loop() {
  reportLastContact("loop start");
  homeSpan.poll();
  reportLastContact("homeSpan poll finished");
  ...
  reportLastContact("loop end");
}

```
and it outputs web log lines like

105 | 0:11:11:47 | Fri Jun 24 11:15:10 2022 | 0.0.0.0 | Last contact 856ms ago. Now at homeSpan poll finished.
104 | 0:10:55:10 | Fri Jun 24 10:58:33 2022 | 0.0.0.0 | Last contact 4108ms ago. Now at homeSpan poll finished.
103 | 0:10:55:03 | Fri Jun 24 10:58:25 2022 | 0.0.0.0 | Last contact 1141ms ago. Now at homeSpan poll finished.
102 | 0:10:10:40 | Fri Jun 24 10:14:02 2022 | 0.0.0.0 | Last contact 716ms ago. Now at homeSpan poll finished.
101 | 0:09:55:16 | Fri Jun 24 09:58:38 2022 | 0.0.0.0 | Last contact 10002ms ago. Now at homeSpan poll finished.
100 | 0:09:55:03 | Fri Jun 24 09:58:25 2022 | 0.0.0.0 | Last contact 1214ms ago. Now at homeSpan poll finished.
99 | 0:09:52:23 | Fri Jun 24 09:55:45 2022 | 0.0.0.0 | Last contact 10001ms ago. Now at homeSpan poll finished.


So I assume between the last loop/update in one of my services, and homeSpan.poll returning to the top level loop, is where it spends 4 seconds. (There are usually a bunch of such long delays within a few minutes, every 2-3 hours or so).

**Comment by cckanne** [comment] 2022-06-24 19:50
I doubt the sensor takes long to return because I never get the "AQ loop end" message, just the "homeSpan poll finished" one.

**Comment by HomeSpan** [comment] 2022-06-25 15:11
One possibility may be the time-clock sync that the ESP automatically does on a periodic basis.  This is activated when you enable the web log output and can take up to 10 seconds before returning (10 seconds is the default timeout).  You can still enable web logging without the time synchronization by setting the time-server to NULL like this: ` homeSpan.enableWebLog(150, NULL, "PST", "zephyr")`.  If the the periodic time-sync is what's causing the issue, this should solve the problem.  The only side-effect of not setting the time will be that the absolute clock time will be incorrect in the weblog output (but all relative times will still be correct).

Whether or not periodic time-syncing is the issue, you may indeed want to try to the new functionality I added to the dev branch described in #304.  Exactly how you do this will depend on what you are doing with the Serial1 port.  Can you describe why you need Serial1 to send messages to your light every second?

More generally, if you have any time-critical functional that needs to run on schedule, you can enable auto-polling (as described in #304 and place your time-critical code in the main Arduino loop() method with a delay.  For example, if you need to send a command via Serial1 every second, you can use:

```C++
void loop(){
  Serial1.print(....);
  delay(1000);
}
```

With auto-polling enabled the `delay(1000)` command will not (well, at least it should not) interfere with HomeSpan polling, which will occur on a separate thread (and separate processor if you are using a two-processor ESP32).  Note that if the Serial command you need to send is contingent on the status of the light (on, off., etc.) you'll need to create some global variables to store the status that can be set by the Home App via the `update()` method of your Light Service, and then read in the main Arduino `loop()` method.  Something like:

```C++
void loop(){
  if(lightOn)
    Serial1.print(lightOnCommand);
  else 
    Serial1.print(lightOffCommand);
  delay(1000);
}
```

**Comment by cckanne** [comment] 2022-06-27 18:37
Thank you. I tried that, but poll() time sometimes still is 4s and there are also are still occasional 10s runs.

I have not yet tried #304 but I have successfully done the "reverse": I have my sensors and the vent hood mainboard to communicate with on a regular schedule. I put the handling of those on a separate tasks/thread each so that they can run even if the main loop is busy with homespan. This seems to successfully allow me to communicate with the mainboard in the required cadence.

BTW, I sent a more elaborate description of the project to homespan@icloud as an email, but as a summary: I also have the zephyr vent hood, and figured out that it has at least two microcontrollers, one on the mainboard, and one behind the capacitative touch controls/status lights. The one on the mainboard sends about 10 msgs per second with the current state of the RF remote control over serial (and probably other status information that I have not sniffed from the protocol yet), and expects the control/status microcontroller to respond back with what the state of the fan and light should be. If sufficient time passes without the mainboard receiving a message, it turns light and fan off. I replaced the control microprocessor with the dual core ESP32.

The separate thread for mainboard comms now just waits for a message from the mainboard, replies with the currently desired state if a complete message was received, and yields the thread back if there is nothing to read from serial right now. Similarly, every few seconds I read the current sensor state in another thread from I2C. I dont use global variables for communication between the homspan callbacks and the threads, but pass a heap pointer in the thread parameters to a common area.

This works well now, and with the #304 improvement I guess I can also have an empty loop().

BTW I am using WEBLOG from all of the threads - is this safe or are there race conditions in the web server/logger?

**Comment by HomeSpan** [comment] 2022-06-29 02:52
I think the solution you arrived at makes a lot of sense - placing time-critical functions each in their own respective threads.  The solution in #304 assumes you would have only one time-critical process remaining in the main `loop()`, so yours is a more general approach.

Re your WEBLOG question, in principle calling the WEBLOG logic from multiple threads could lead to some collisions since the WEBLOG code was not programmed to be thread safe, but if it seems to work, I guess that means the chance of collision is very low.

I did not get your direct email about the details - can you resend?  What a coincidence that you also have a Zephyr Vent Hood.  I love the hood - it works great.  But the remote control that came with my model was terrible.  The manufacturer sent me a replacement but the problem is in the design itself.  Rather than have physical buttons, the remote uses capacitive touch sensors that are not calibrated correctly.  It hardly every registered a touch so to turn the fan on I had to press the button 50-100 times and hope to get lucky.  It was this frustration that ultimately led me to create HomeSpan.  However, I took a somewhat different approach and created an Accessory that simply mimics the buttons on the original remote and transmits the same RF codes.  Sounds like you took a more direct route and hardwired your ESP32 directly to the control board of the vent, which I'm guessing may also give you some more flexibility in how to control the fan, fan speed, light, and light brightness.  Very cool!

**Closed** 2022-12-30 03:43 UTC
