### ISSUE TITLE
Running update loop twice

### ISSUE THREAD

**Issue by maragelis** [HomeSpan/HomeSpan#21] opened 2021-01-20 07:21 UTC
Thanks for a great library, I have noticed that using the thermostat service, the update loop runs twice. Is this by design or is there something going on. 

I have attached my sketch. 

[Homekit_mitsubishi.txt](https://github.com/HomeSpan/HomeSpan/files/5840727/Homekit_mitsubishi.txt)

**Comment by HomeSpan** [comment] 2021-01-20 14:00
I'll take a look and see if I can reproduce/debug.

**Comment by HomeSpan** [comment] 2021-01-23 21:06
Thanks for sending me your code.  After commenting out the sections of your sketch that send (infrared?) signals to the actual AC unit, I was able to compile and run.  If I change the target state to HEAT or COOL things work fine, but if I change to AUTO, any new iOS device that tries to read/control the thermostat fails and the Home App indicates the device is unresponsive.

The problem lies in the following lines of your loop function:

```C++
    if (currState->timeVal()>5000)
    {
       currState->setVal(targState->getVal()); 
    }
```

In HomeKit, TargetHeatingCoolingState (*targState*) and CurrentHeatingCoolingState (*currState*) are not mirror images of each other.  HomeKit nomenclature is very inconsistent across different services - for a thermostat *targState* actually refers to the "mode" of a traditional Thermostat: OFF (0), HEAT (1), COOL (2), or AUTO (3).  Apple really should have called this "HeatingCoolingMode" or something like that.  In contrast, *currState* refers the actual current operating state, which can be set to OFF (0), HEAT (1), or COOL (2), but **not** AUTO (3).   To avoid confusion, Apple really should have named these "Idle", "Heating" and "Cooling", which, ironically, is what Apple does display for this characteristic in the Home App.  

Note that 3 is not a valid *currState*.  But in your code, you are updating *currState* to match *targState*.  If *targState* is set to auto, this results in *currState* being set to an invalid value.  

From my own testing it appears that if already open, the Home App does not validate *currState* when it receives an event notification, so it seems to ignore the fact that *currState* is incorrectly set to 3.  But if you close the Home App and open it again, HomeKit requests a full list of characteristics from the device AND validates the response.  If it finds *currState* is set to 3, it causes Home App to indicate the device is unresponsive (which basically means something is wrong, but it won't tell you what).

The solution is to rework your logic so that you periodically check to see if the AC unit is heating, cooling, or idle, and then update *currState* accordingly.  This may not be possible if you don't have any feedback from the AC unit, in which case an alternative would be to assume the state of the AC unit by comparing the target temperature to the current temperature.

For example, if the target temp is more than 0.5 degrees above the current temp, AND *targState* is set to HEAT or AUTO, you can set *currState* to Heating (1).  Else, if the target temp is less than 0.5 degrees below the current temp, AND *targState* is set to COOL or AUTO, you can set the *currState* to Cooling (2).  If none of those conditions hold, set *currState* to Idle (0).

Note it's generally a good practice to try to minimize notification updates back to HomeKit (i.e. using `setVal()`).  So rather than use `timeVal()` to reset the state every 5 seconds, you can invoke the logic above every time the loop() runs, and compare the result (Idle/Heating/Cooling) to *currState*.  If its different, update *currState* to that new value.  If not, do nothing.

The parts of your loop code (not shown above) that read and update the temperature seem fine.  Note however that temperature is a float, not an integer, so whenever you read its target value you should use `getNewVal<float>()` instead of just `getNewVal()`.  Also note that neither of these will return a valid value until a target temperature is requested by the Home App.  In the first part of your `update()` method you print out the new values for *targState* and *targTemp*.  One of those will not contain a meaningful number until it is specifically updated by the Home App at least once. (We know at least one of them **will** contain a real number, since the call to update() means the Home App requested at least one of them to be changed.)

As to your initial question about duplicate calls to `update()`, I wish I knew the answer.  This seems to be a bug in HomeKit that I have encountered in various forms while developing HomeSpan.  Or perhaps it's on my side and there's a response HomeKit is expecting that I'm unaware of, and failed to incorporate into HomeSpan.

If you set the Log Message Level to 2, you'll see that the Home App is indeed requesting two updates every time you change the mode (i.e. from OFF to COOL).  The requests are identical and the second requests comes right after the first.  Interestingly, this **only** occurs when changing the mode.  It does **not** happen when you change the temperature.  In that case the Home App sends just one update request.  Setting the mode and setting the temperature use the same exact mechanisms, so I can't even guess why HomeKit insists on sending two updates for every mode change.  This is why I think it may be a bug of some sort in HomeKit rather than in HomeSpan.  But I'd be more than happy to be wrong so I can fix it!

It does look like you handle this gracefully in your sketch by checking whether `targetState->getNewVal()` is indeed different than `targetState->getVal()`.  This seems like a good solution to handle repeated calls from HomeKit.

I hope the explanations above help.  Please let me know if this solves the problems.

**Comment by maragelis** [comment] 2021-01-24 10:39
Thanks for a great explanation, after two three years working with homebridge I could never get target and current states in my head. Thanks a lot.

**Comment by HomeSpan** [comment] 2021-01-24 13:16
Glad to help.  I'll close the issue for now - please let me know if any other problems arise.

**Closed by HomeSpan** 2021-01-24 13:16 UTC
